---
language: generic

env:
  global:
  - PACKAGE_NAME=openexo-wallpapers

before_install:
- export BUILD_VERSION=$(date "+%Y%m%d").$TRAVIS_BUILD_NUMBER
- if [ ! -z "$TRAVIS_TAG" ]; then export BUILD_VERSION=$TRAVIS_TAG; fi
- export PACKAGE_NAME_VERSION=$PACKAGE_NAME.$BUILD_VERSION.deb
- sudo apt-get install -y devscripts

script:
- if [ ! -z "$TRAVIS_TAG" ]; then sed -i "s/0.0.0/$TRAVIS_TAG/" $PACKAGE_NAME/DEBIAN/control; fi
- bash generate.sh
- dpkg-deb --build $PACKAGE_NAME
- mv $PACKAGE_NAME.deb $PACKAGE_NAME_VERSION
- mv $PACKAGE_NAME/DEBIAN $PACKAGE_NAME/debian
- mv $PACKAGE_NAME $PACKAGE_NAME.0.0.1
- cd $PACKAGE_NAME.0.0.1 && debuild -S -sa -k$GPG_KEY
- dput ppa:openexo/openexo-wallpapers "$PACKAGE_NAME.$BUILD_VERSION"_source.changes

after_success:
- ls -l $PACKAGE_NAME_VERSION
- md5sum $PACKAGE_NAME_VERSION
- dpkg --contents $PACKAGE_NAME_VERSION
- git add openexo-wallpapers/openexo-wallpapers.xml
- git commit -am "New upstream"

# Check this https://docs.travis-ci.com/user/deployment/launchpad/
deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file: "$PACKAGE_NAME_VERSION"
    skip_cleanup: true
    on:
      tags: true       
  - provider: launchpad
    slug: "~openexo/openexo/+git/openexo"
    oauth_token: "$LP_OAUTH_TOKEN"
    oauth_token_secret: "$LP_OAUTH_TOKEN_SECRET"
    on:
      tags: true

      