language: generic
env:
  global:
  - PACKAGE_NAME=openexo-wallpapers
  - GPG_KEY:
      secure: sxYa7UGH2Nd+LVUkeisjdf3E6/QVU8UQhdZVC4AcIu9Ueecj0PYl1b+v3WhnV+tfM+iJot304oAvwgsh8UfB74dZTZ+msrJUUadJknU7vqQi1/ZnovhqPQSgpoD0ZW/SWgTSqx7aSWqcL1JfvCHmreBziLAFSAY05kNedRETUKnk4Yll6WZoOIr1jIpkvc9MRQGYTGlEATwcH/uPI9QfhkcQiS32/Fw9Tsc3r3ji2Nr2NgUoCH0AVmZbfGJkzKOFVHtfOlxEQy5l7oGiAmjjzqesEIXjaxd0b56yIxtomKYjnWMEXcUYNurdmr+WZ3ock8lTuBSiIImnHVabdOXgWx2sSGYfQtWF/YV4BckP74TAiak/Jp3FJTz64kEi75Ro0ndZTZuqk4l11jV+QRgz7AuHbxHvmMsj3LTlSiJVFGtqYM1iEvQ6dFyO5kwZEjZYLRRBXVHHuXJl56f1F4IVmjj/36yT854bW8HtCwiX42cnZzRTSgM0UJ/tSJu9D8nZppKbiqGSDZ0tR8izjVhSBZs0QLsBaw2WvretNk4UB36fBYr+e7kO7Jubq6NiLwkL4ZHgVv7HtarTMC628nz13VGLFls+w00damChXXNUUs4I4+GuMVSV2byBrtBwF+gRASHxY/Y2kD78dGHrYmZRpIHCVmo27xR1+E0eH9fhDWs=
before_install:
- openssl aes-256-cbc -K $encrypted_1c674c9d5ecc_key -iv $encrypted_1c674c9d5ecc_iv
  -in all.gpg.enc -out all.gpg -d
- gpg --import all.gpg
- export BUILD_VERSION=$(date "+%Y%m%d").$TRAVIS_BUILD_NUMBER
- if [ ! -z "$TRAVIS_TAG" ]; then export BUILD_VERSION=$TRAVIS_TAG; fi
- export PACKAGE_NAME_VERSION=$PACKAGE_NAME.$BUILD_VERSION.deb
- sudo apt-get install -y devscripts
- sudo apt-get install -y fakeroot
- sudo apt-get install -y dh-make
script:
- if [ ! -z "$TRAVIS_TAG" ]; then sed -i "s/0.0.0/$TRAVIS_TAG/" $PACKAGE_NAME/DEBIAN/control;
  fi
- bash generate.sh
- dpkg-deb --build $PACKAGE_NAME
- mv $PACKAGE_NAME.deb $PACKAGE_NAME_VERSION
- mv $PACKAGE_NAME/DEBIAN $PACKAGE_NAME/debian
- mv $PACKAGE_NAME $PACKAGE_NAME.0.0.1
- cd $PACKAGE_NAME.0.0.1 && debuild -d -S -sa -k$GPG_KEY
- cd .. && dput ppa:openexo/openexo-wallpapers  openexo-wallpapers_0.0.18_source.changes
after_success:
- ls -l $PACKAGE_NAME_VERSION
- md5sum $PACKAGE_NAME_VERSION
- dpkg --contents $PACKAGE_NAME_VERSION
- git add openexo-wallpapers/openexo-wallpapers.xml
- git commit -am "New upstream"
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "$PACKAGE_NAME_VERSION"
  skip_cleanup: true
  on:
    tags: true
- provider: launchpad
  slug: "~openexo/openexo/+git/openexo"
  oauth_token: "$LP_OAUTH_TOKEN"
  oauth_token_secret: "$LP_OAUTH_TOKEN_SECRET"
  on:
    tags: true