Document: wallpaperexo
Title: Debian wallpaperexo Manual
Author: <insert document author here>
Abstract: This manual describes what wallpaperexo is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wallpaperexo/wallpaperexo.sgml.gz

Format: postscript
Files: /usr/share/doc/wallpaperexo/wallpaperexo.ps.gz

Format: text
Files: /usr/share/doc/wallpaperexo/wallpaperexo.text.gz

Format: HTML
Index: /usr/share/doc/wallpaperexo/html/index.html
Files: /usr/share/doc/wallpaperexo/html/*.html
